### ISSUE TITLE
Instrumenting of django failed

### ISSUE THREAD

**Issue by famoushz** [open-telemetry/opentelemetry-operator#1080]
Hello 
I tried to 
https://github.com/SigNoz/sample-django

**Comment by famoushz** [comment]
@pavolloffay @jpkrohling @VineethReddy02 can you help ?

**Comment by famoushz** [comment]
@pavolloffay @jpkrohling @VineethReddy02 or anyone can you help ?

**Comment by pavolloffay** [comment]
I won't be able to help with python. Perhaps you can reach out to somebody form the python community.

**Comment by famoushz** [comment]
@pavolloffay  this is not some python issue, all has been tested in Docker file with autoinstrumenation lib is working properly, but if used autoinstrumenation from opentelemetry sidecar, got above errors said module not found.

**Comment by TylerHelmuth** [comment]
@famoushz can you try adding `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL` to the Instrumentation's env vars?

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://tempo:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: 'http/protobuf'
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
```

**Comment by flenoir** [comment]
Hi, 

I think i have same kind of issue.

I have a Django app deployed on kubernetes. Application is working quite well

When i add python injection. the app is restarting and an init-container is launched as expected but application has below error :

```

│ djangoapp   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                                                                                                  │
│ djangoapp ModuleNotFoundError: No module named 'bookswap_project'                                                                                                                                       │
│ djangoapp Failed to auto initialize opentelemetry                                                                                                                                                       │
│ djangoapp Traceback (most recent call last):                                                                                                                                                            │
│ djangoapp   File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 122, in initialize                                                              │
│ djangoapp     _load_instrumentors(distro)                                                                                                                                                               │
│ djangoapp   File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 88, in _load_instrumentors                                                      │
│ djangoapp     raise exc                                                                                                                                                                                 │
│ djangoapp   File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 84, in _load_instrumentors                                                      │
│ djangoapp     distro.load_instrumentor(entry_point, skip_dep_check=True)                                                                                                                                │
│ djangoapp   File "/otel-auto-instrumentation/opentelemetry/instrumentation/distro.py", line 63, in load_instrumentor                                                                                    │
│ djangoapp     instrumentor().instrument(**kwargs)                                                                                                                                                       │
│ djangoapp   File "/otel-auto-instrumentation/opentelemetry/instrumentation/instrumentor.py", line 110, in instrument                                                                                    │
│ djangoapp     **kwargs                                                                                                                                                                                  │
│ djangoapp   File "/otel-auto-instrumentation/opentelemetry/instrumentation/django/__init__.py", line 267, in _instrument                                                                                │
│ djangoapp     settings_middleware = getattr(settings, _middleware_setting, [])                                                                                                                          │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__                                                                                              │
│ djangoapp     self._setup(name)                                                                                                                                                                         │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup                                                                                                   │
│ djangoapp     self._wrapped = Settings(settings_module)                                                                                                                                                 │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__                                                                                                │
│ djangoapp     mod = importlib.import_module(self.SETTINGS_MODULE)                                                                                                                                       │
│ djangoapp   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module                                                                                                           │
│ djangoapp     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                               │
│ djangoapp   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                                                                             │
│ djangoapp   File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                                           │
│ djangoapp   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                                                                                                  │
│ djangoapp   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                                                │
│ djangoapp   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                                                                             │
│ djangoapp   File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                                           │
│ djangoapp   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                                                                                                  │
│ djangoapp ModuleNotFoundError: No module named 'bookswap_project'                                                                                                                                       │
│ djangoapp [2023-03-06 14:35:53 +0000] [1] [INFO] Starting gunicorn 20.1.0                                                                                                                               │
│ djangoapp [2023-03-06 14:35:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)                                                                                                                  │
│ djangoapp [2023-03-06 14:35:53 +0000] [1] [INFO] Using worker: sync                                                                                                                                     │
│ djangoapp [2023-03-06 14:35:53 +0000] [9] [INFO] Booting worker with pid: 9 


```

regarding instrumentation manifest, here's a part of the manifest concerning python 

  ```
python:
    # image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
    env:
      - name: OTEL_COMPONENT
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['component']
      - name: OTEL_CADRE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['cadre']
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://opentelemetry-collector.monitoring:4318/v1/traces
      # - name: OTEL_LOGS_EXPORTER
      #   value: none
      # - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
      #   value: http://opentelemetry-collector.monitoring:4318
      - name: OTEL_METRICS_EXPORTER
        value: none
      # - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
      #   value: http://opentelemetry-collector.monitoring:4318
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: 'http/protobuf'
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: 'http/protobuf'
```

i noticed that if i uncomment the python image, then a get the latest one as expected but, this time the error is different :

```
│ djangoapp [2023-03-06 14:42:40 +0000] [1] [INFO] Starting gunicorn 20.1.0                                                                                                                               │
│ djangoapp [2023-03-06 14:42:40 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)                                                                                                                  │
│ djangoapp [2023-03-06 14:42:40 +0000] [1] [INFO] Using worker: sync                                                                                                                                     │
│ djangoapp [2023-03-06 14:42:40 +0000] [9] [INFO] Booting worker with pid: 9                                                                                                                             │
│ djangoapp [2023-03-06 14:42:48 +0000] [9] [ERROR] Error handling request /accounts/signup/                                                                                                              │
│ djangoapp Traceback (most recent call last):                                                                                                                                                            │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 136, in handle                                                                                                 │
│ djangoapp     self.handle_request(listener, req, client, addr)                                                                                                                                          │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 179, in handle_request                                                                                         │
│ djangoapp     respiter = self.wsgi(environ, resp.start_response)                                                                                                                                        │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 141, in __call__                                                                                           │
│ djangoapp     response = self.get_response(request)                                                                                                                                                     │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 74, in get_response                                                                                        │
│ djangoapp     set_urlconf(settings.ROOT_URLCONF)                                                                                                                                                        │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__                                                                                              │
│ djangoapp     val = getattr(self._wrapped, name)                                                                                                                                                        │
│ djangoapp   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 222, in __getattr__                                                                                             │
│ djangoapp     return getattr(self.default_settings, name)                                                                                                                                               │
│ djangoapp AttributeError: module 'django.conf.global_settings' has no attribute 'ROOT_URLCONF'


```

i checked many times my settings file but it seems ok, please find it below : 
```
import os

DEBUG = False
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

ALLOWED_HOSTS = ['*']

# SECRET_KEY = '[HIDDEN]'
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '[HIDDEN]'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('SQL_DATABASE'),
        'USER': os.getenv('SQL_USER'),
        'PASSWORD': os.getenv('SQL_PASSWORD'),
        'HOST': os.getenv('SQL_HOST'),
        'PORT': os.getenv('SQL_PORT', 5432)
     }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'fontawesome_5',
    'crispy_forms',
    'search',
    'users',
    'pages',
    'invitations',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookswap_project.urls'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookswap_project.wsgi.application'

# Static files settings

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))  # reference sur chemin du fichier en cours
#STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')  
#STATIC_ROOT  = '/app/bookswap/static' # localisation dans docker
#STATIC_URL = '/static/'
STATIC_ROOT = 'bookswap/static'
# Extra places for collectstatic to find static files. 
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
#     'static'
# )   

STATIC_URL = '/static/'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USERNAME_REQUIRED = False

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '[HIDDEN]',
            'secret': '[HIDDEN]',
            'key': ''
        }
    }
}

LOGIN_REDIRECT_URL = 'main'
LOGOUT_REDIRECT_URL = 'main'
ACCOUNT_LOGOUT_ON_GET = False


INTERNAL_IPS = [
    '127.0.0.1',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL = '[HIDDEN]'
EMAIL_HOST_PASSWORD = ''[HIDDEN]''

CRISPY_TEMPLATE_PACK = 'bootstrap4'

```

Again, if i remove python-injection annotation and restart pod, the application works.

Do you have any idea on this ? 

regards

**Comment by TylerHelmuth** [comment]
@flenoir Can you try removing /v1/traces from the OTEL_EXPORTER_OTLP_ENDPOINT value?

**Comment by flenoir** [comment]
Hi @TylerHelmuth, i just did try but still have same error message regarding URLCONF

**Comment by srikanthccv** [comment]
@flenoir can you configure `DJANGO_SETTINGS_MODULE` to the settings file and check? If you could share a simple reproducible Django app that would be very helpful.

**Comment by sungmincs** [comment]
I had a similar issue and it took me a while to figure out why the config is not loaded properly. 
It turns out that when auto instrumentation is enabled, the opentelemetry uses its binary path as a default PYTHONPATH, and this results in ignoring the setting configs for the django application.
As stated in the issue below, including the path of your project root to `PYTHONPATH` will help the `otel-auto-instrumentation-python` understand where your project settings are, and it did fix the issue for me.
```
# spec.env
        env:
        - name: PYTHONPATH
          value: "/app"    # root of your project
```
and this `/app` path gets properly appended to `PYTHONPATH` in the pod.
```
$ kubectl exec -it myapp-77764c4894-7kwzw -- env | grep PYTHONPATH
Defaulted container "myapp" out of: myapp, opentelemetry-auto-instrumentation-python (init)
PYTHONPATH=/otel-auto-instrumentation-python/opentelemetry/instrumentation/auto_instrumentation:/app:/otel-auto-instrumentation-python
```
and this fixes the issue for me. 

related issues that helped me:
- https://github.com/open-telemetry/opentelemetry-operator/issues/2302
- https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2023

**Comment by golgor** [comment]
I had the issues as described above as well and the solution from @sungmincs fixed it! Thanks a lot!

For me I tried to set the values for DJANGO_SETTINGS_MODULE and PYTHONPATH in a ConfigMap. When checking the environment the values where there and everything looked good, but I kept getting the errors. Setting them in the `env` of the deployment fixed everything. No idea why. Maybe the ConfigMap is applied after the autoinstrumentation somehow?
