### ISSUE TITLE
Setting maxReplicas causes runtime panic

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-operator#1197]
I can take any working configuration, set `maxReplicas` and observe this failure.

```
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: {"level":"info","ts":1666468160.274646,"logger":"opentelemetrycollector-resource","msg":"default","name":"observiq-gateway"}
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 2022/10/22 19:49:20 http: panic serving 172.16.10.6:56060: runtime error: invalid memory address or nil pointer dereference
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: goroutine 4255 [running]:
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.(*conn).serve.func1()
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:1850 +0xbf
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: panic({0x24e3160, 0x410ab60})
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/runtime/panic.go:890 +0x262
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: github.com/open-telemetry/opentelemetry-operator/apis/v1alpha1.(*OpenTelemetryCollector).Default(0xc0009faa80)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/workspace/apis/v1alpha1/opentelemetrycollector_webhook.go:71 +0x2a4
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*mutatingHandler).Handle(_, {_, _}, {{{0xc0011e2390, 0x24}, {{0xc000dbd890, 0x10}, {0xc000dbd8a0, 0x8}, {0xc000d122d0, ...}}, ...}})
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/defaulter.go:79 +0x259
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc0011e2390, 0x24}, {{0xc000dbd890, 0x10}, {0xc000dbd8a0, 0x8}, {0xc000d122d0, ...}}, ...}})
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/webhook.go:169 +0xfd
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000124740, {0x7f7eee6fe238?, 0xc0000a2000}, 0xc0010be900)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/webhook/admission/http.go:98 +0xeb5
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f7eee6fe238, 0xc0000a2000}, 0x2ddff00?)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:40 +0xd4
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.HandlerFunc.ServeHTTP(0x2ddfff8?, {0x7f7eee6fe238?, 0xc0000a2000?}, 0xc0008f7a68?)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:2109 +0x2f
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x2ddfff8?, 0xc0006707e0?}, 0xc0010be900)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:117 +0xaa
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.HandlerFunc.ServeHTTP(0xc0008f79e0?, {0x2ddfff8?, 0xc0006707e0?}, 0xe0?)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:2109 +0x2f
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x2ddfff8, 0xc0006707e0}, 0xc0010be900)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/instrument_server.go:84 +0xbf
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.HandlerFunc.ServeHTTP(0xc0006707e0?, {0x2ddfff8?, 0xc0006707e0?}, 0x299faca?)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:2109 +0x2f
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.(*ServeMux).ServeHTTP(0xc0010de33e?, {0x2ddfff8, 0xc0006707e0}, 0xc0010be900)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:2487 +0x149
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.serverHandler.ServeHTTP({0x2dd2bd0?}, {0x2ddfff8, 0xc0006707e0}, 0xc0010be900)
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:2947 +0x30c
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: net/http.(*conn).serve(0xc0003480a0, {0x2de1218, 0xc0006978c0})
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:1991 +0x607
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: created by net/http.(*Server).Serve
opentelemetry-operator-system/opentelemetry-operator-controller-manager-77bfb5b896-nk68q[manager]: 	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

Removing maxReplicas resolves the problem. The client (kubectl) returns the following error, which seems to line up with the panic.
```
for: "STDIN": Internal error occurred: failed calling webhook "mopentelemetrycollector.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s": EOF
```

Example config:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector
spec:
  config: |
    receivers:
      nop:
        
    exporters:
      nop:

    service:
      pipelines:
        metrics:
          receivers:
            - nop
          exporters:
            - nop

  replicas: 2
  maxReplicas: 5
  mode: deployment
```

**Comment by kevinearls** [comment]
I think I have a fix for this and will submit a PR shortly
