### ISSUE TITLE
Dotnet auto-instrumentation injection: Could not load file or assembly `Google.Protobuf`

### ISSUE THREAD

**Issue by Nemeczek** [open-telemetry/opentelemetry-operator#1399]
Auto instrumentation injection crashes on startup. When I try to inject auto-instrumentation it fails with the Google.Protobuf error. 

- /azure-functions/dotnet:4 docker image so system is Debian 11
- OS: Debian 11
- .NET version: 6
- Operator: v0.67.0 

instrumentation.yml
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: redacted
  namespace: redacted
spec:
  exporter:
    endpoint: redacted
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"

```

deployment.yml:
```
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-dotnet: "true"
```

````
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.AutoInstrumentation.Loader.Startup' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileLoadException: Could not load file or assembly 'Google.Protobuf, Version=3.19.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. Could not find or load a specific file. (0x80131621)
File name: 'Google.Protobuf, Version=3.19.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Google.Protobuf, Version=3.19.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at OpenTelemetry.Exporter.OtlpTraceExporter..ctor
   at OpenTelemetry.Trace.OtlpTraceExporterHelperExtensions.AddOtlpExporter(TracerProviderBuilder builder, OtlpExporterOptions exporterOptions, Action`1 configure, IServiceProvider serviceProvider, Func`2 configureExporterInstance)
   at OpenTelemetry.AutoInstrumentation.Configuration.EnvironmentConfigurationTracerHelper.Wrappers.AddOtlpExporter(TracerProviderBuilder builder, TracerSettings settings, PluginManager pluginManager) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationTracerHelper.cs:line 185
   at OpenTelemetry.AutoInstrumentation.Configuration.EnvironmentConfigurationTracerHelper.SetExporter(TracerProviderBuilder builder, TracerSettings settings, PluginManager pluginManager) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationTracerHelper.cs:line 79
   at OpenTelemetry.AutoInstrumentation.Configuration.EnvironmentConfigurationTracerHelper.UseEnvironmentVariables(TracerProviderBuilder builder, LazyInstrumentationLoader lazyInstrumentationLoader, TracerSettings settings, PluginManager pluginManager) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationTracerHelper.cs:line 57
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:line 119
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenTelemetry.AutoInstrumentation.Loader.Startup.TryLoadManagedAssembly() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.Loader/Startup.cs:line 52
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..cctor() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.Loader/Startup.cs:line 47
   --- End of inner exception stack trace ---
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at StartupHook.Initialize() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.StartupHook/StartupHook.cs:line 68
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
````

**Comment by Nemeczek** [comment]
Hey,
@open-telemetry/dotnet-instrumentation-maintainers

I am working on the [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
Probably will have it tomorrow. It took me some time to setup minikube. 

What I already noticed that with the same set of nuget packages that if I use as base image:
```
mcr.microsoft.com/dotnet/runtime:6.0 AS base
```
It works. 
But when I use:
```
mcr.microsoft.com/azure-functions/dotnet:4
```
It failes with the protobuff error. I will dig more tomorrow

**Comment by Nemeczek** [comment]
I think I got it. 

https://github.com/Nemeczek/af-dotnet-repro/tree/main/ConsoleApp4

It is a plain console app that runs normally on runtime image. On Azure Functions one fails with the mentioned error. 

@open-telemetry/dotnet-instrumentation-maintainers I hope is that makes sense as Minimal, Repoducible Example.

**Comment by Kielek** [comment]
@Nemeczek, sorry for late response but the output when I am trying just to execute docker image (even without k8s)
leads to 
`start container process: exec: "dotnet": executable file not found in $PATH: unknown`.

The latest Docker for Windows (Linux containers).

**Comment by swiatekm-sumo** [comment]
I'm closing this due to lack of recent communication from the issue author. @Nemeczek please feel free to reopen if you'd like to continue the conversation.
