### ISSUE TITLE
operator-controller-manager pod crashing with SIGSEGV error when using custom otel collector image

### ISSUE THREAD

**Issue by himamulch** [open-telemetry/opentelemetry-operator#1558]
Hi,
I've an EKS cluster setup up and running using otel contrib image at 
https://docker.io/otel/opentelemetry-collector-contrib
and operator image at https://ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator (v0.66.0).  

However, when I update the collector image to point to my custom collector image, the operator-controller-manager pod is crashing with the below SIGSEGV error:
_{"level":"info","ts":1677684575.5896716,"msg":"Starting workers","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","worker count":1}
{"level":"info","ts":1677684575.6121721,"logger":"controllers.OpenTelemetryCollector","msg":"receiver's endpoint isn't a string","opentelemetrycollector":"opentelemetry/app-metrics"}
{"level":"info","ts":1677684575.6126862,"logger":"controllers.OpenTelemetryCollector","msg":"receiver's endpoint isn't a string","opentelemetrycollector":"opentelemetry/app-metrics"}
{"level":"info","ts":1677684575.6953118,"logger":"controllers.OpenTelemetryCollector","msg":"receiver's endpoint isn't a string","opentelemetrycollector":"opentelemetry/app-metrics"}
{"level":"info","ts":1677684575.7184412,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","OpenTelemetryCollector":{"name":"app-metrics","namespace":"opentelemetry"},"namespace":"opentelemetry","name":"app-metrics","reconcileID":"a6e9093a-0fb9-44a9-bdab-ec4ed98dfb3b"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x204fdf3]
goroutine 456 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x24e9720, 0x4115d80})
        /usr/local/go/src/runtime/panic.go:884 +0x212
[github.com/open-telemetry/opentelemetry-operator/pkg/collector.HorizontalPodAutoscaler](https://github.com/open-telemetry/opentelemetry-operator/pkg/collector.HorizontalPodAutoscaler)({{0x2dd65c0, 0xc0002b62a0}, 0x0, {{0x2decdb8, 0xc00051b380}, 0x0}, {0x7fff5473bd91, 0xb3}, {0xc00013cd20, 0x4f}, ...}, ...)
        /workspace/pkg/collector/horizontalpodautoscaler.go:88 +0x5f3_

The collector pod is up and running fine.  I've also tested the collector in standalone mode and it seems to be fine.  Could you please advice if I need to make sure of any configuration while building the docker image of custom collector.

This is my Dockerfile config:
FROM <host>/<path>/<base>/lrh:8-stable
COPY bin/opentelemetry-collector-contrib-custom /opentelemetry-collector-contrib-custom
ENTRYPOINT ["/opentelemetry-collector-contrib-custom"]
CMD ["--config", "/etc/otel/config.yaml"] 

Please let me know if there is any other information required.

Thanks

**Comment by moh-osman3** [comment]
A couple of questions I'm curious to know:
1. Is there are reason you are running an outdated version of the operator? current release is `v0.71.0`. Upgrading to the latest will help determine if there is a bug that currently exists in the operator that needs to be resolved.
2. What does your configuration/spec look like for the operator's OpenTelemetryCollector CRD? Full config would be helpful and curious what are you setting for [Collector Image](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go#L119)

From my experience the operator creates the collector pod by pulling the collector image from dockerhub, so if you set `otel/opentelemetry-collector-contrib:latest` then this will fetch the image from [otel/opentelemetry-collector-contrib docker repo](https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags). Is this custom image pushed to and available in a dockerhub repo?

**Comment by himamulch** [comment]
Hello, Thanks for looking into this.
Unfortunately I cannot use v0.71.0 as the latest version available within our firm is 0.66.0 at the moment.  Would it be possible to debug with v0.66.0 itself?

I've attached the CRDs, operator deployment config and the values.
[op-ctrl-mgr-pod-issue.zip](https://github.com/open-telemetry/opentelemetry-operator/files/10920149/op-ctrl-mgr-pod-issue.zip)

Thanks

**Comment by weiwu-sre** [comment]
This happens to my operator today. When I removed HPA configuration on collector, the panic stopped.

**Comment by moh-osman3** [comment]
@weiwu-sre Hmm perhaps this is a bug in the HPA. Would you mind sharing what your HPA config was before you removed it? Were you using the internal HPA described in the [collector CRD Spec](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go#L97)? (Also described in the [API docs](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspecautoscaler))

**Comment by weiwu-sre** [comment]
Here is the diff.
```
 spec:
   mode: deployment
-  minReplicas: 2
-  maxReplicas: 10
-  autoscaler:
-    # targetCPUUtilization only support > 1 and < 99
-    targetCPUUtilization: 95
-    behavior:
-      scaleUp:
-        stabilizationWindowSeconds: 60
-      scaleDown:
-        stabilizationWindowSeconds: 1800
+  replicas: 3
+  # minReplicas: 2
+  # maxReplicas: 10
+  # autoscaler:
+  #   # targetCPUUtilization only support > 1 and < 99
+  #   targetCPUUtilization: 95
+  #   behavior:
+  #     scaleUp:
+  #       stabilizationWindowSeconds: 60
+  #     scaleDown:
+  #       stabilizationWindowSeconds: 1800
```

**Comment by moh-osman3** [comment]
@himamulch not quite sure what's going on.  I could successfully run your operator deployment helm chart, but I'm curious 1. what config you're running for your collector? Are you using a separate helm chart? Seeing a configmap of your collector would be helpful. The operator seems to be having trouble reading something in the config of your custom collector.
2. Are you configuring autoscaling at all?

@weiwu-sre I added your config to my cluster and it seems to work fine for my operator deployment. Any other details about your config to help reproduce the issue? Maybe filing a separate issue would be helpful here

**Comment by moh-osman3** [comment]
@himamulch I also noticed your deployment has 

```
admissionWebhooks:
  failurePolicy: Fail
  enabled: false
```

I wonder if setting this to true will help in the case that something is not getting set properly and causing this segfault

**Comment by frzifus** [comment]
The chance is high that enabling the webhook will fix your issues. Since the default webhook provides missing values.

**Comment by himamulch** [comment]
> @himamulch not quite sure what's going on. I could successfully run your operator deployment helm chart, but I'm curious 1. what config you're running for your collector? Are you using a separate helm chart? Seeing a configmap of your collector would be helpful. The operator seems to be having trouble reading something in the config of your custom collector. 2. Are you configuring autoscaling at all?
> 
> @weiwu-sre I added your config to my cluster and it seems to work fine for my operator deployment. Any other details about your config to help reproduce the issue? Maybe filing a separate issue would be helpful here

@moh-osman3  @frzifus 
Its the same issue when I enable the webhook.  Let me try with the change that worked for @weiwu-sre

**Comment by himamulch** [comment]
@moh-osman3 
The pod seems to be running fine now after removing the _minReplicas_ & _maxReplicas_ on collector.

**Comment by himamulch** [comment]
@weiwu-sre are you also trying with a custom collector image?

**Comment by weiwu-sre** [comment]
> @weiwu-sre are you also trying with a custom collector image?

No. I am not using any custom collector images.

**Comment by moh-osman3** [comment]
Strange I can only reproduce this same error when I disable the webhook.  There might be something preventing communication with the webhook.  I wonder if you're running a cert-manager? From the helm operator readme it seems that without certs properly set up this can prevent communication with the webhook

Also just as a sanity check, can you also reproduce the error and check in the operator logs whether you see information about the webhook starting?

**Comment by weiwu-sre** [comment]
Yup. I have cert manager running and here is the output of issued cert from cert manager.

### Certificate resource
```
❯ k get cert
NAME                                                READY   SECRET                                                                 AGE
otlp-operator-opentelemetry-operator-serving-cert   True    otlp-operator-opentelemetry-operator-controller-manager-service-cert   5d10h
```

```
❯ k describe cert otlp-operator-opentelemetry-operator-serving-cert
Name:         otlp-operator-opentelemetry-operator-serving-cert
Namespace:    sre
Labels:       app.kubernetes.io/component=webhook
              app.kubernetes.io/instance=otlp-operator
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=opentelemetry-operator
              app.kubernetes.io/version=0.70.0
              helm.sh/chart=opentelemetry-operator-0.24.1
Annotations:  meta.helm.sh/release-name: otlp-operator
              meta.helm.sh/release-namespace: sre
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Resource Version:  3997829585
  UID:               279a4034-efe4-42d1-ade3-8af1334fc511
Spec:
  Dns Names:
    otlp-operator-opentelemetry-operator-webhook.sre.svc
    otlp-operator-opentelemetry-operator-webhook.sre.svc.cluster.local
  Issuer Ref:
    Kind:       Issuer
    Name:       otlp-operator-opentelemetry-operator-selfsigned-issuer
  Secret Name:  otlp-operator-opentelemetry-operator-controller-manager-service-cert
  Subject:
    Organizational Units:
      otlp-operator-opentelemetry-operator
Status:
  Conditions:
    Last Transition Time:  2023-03-09T06:50:07Z
    Message:               Certificate is up to date and has not expired
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2023-06-07T06:50:07Z
  Not Before:              2023-03-09T06:50:07Z
  Renewal Time:            2023-05-08T06:50:07Z
  Revision:                1
Events:                    <none>
```

### Here is output during operator pod start-up
```
I0314 17:23:51.032644       1 main.go:186] Valid token audiences:
I0314 17:23:51.032702       1 main.go:316] Generating self signed cert as no cert is provided
I0314 17:23:51.923410       1 main.go:366] Starting TCP socket on 0.0.0.0:8443
I0314 17:23:51.923620       1 main.go:373] Listening securely on 0.0.0.0:8443
{"level":"info","ts":1678814628.1471705,"msg":"Starting the OpenTelemetry Operator","opentelemetry-operator":"0.70.0","opentelemetry-collector":"otel/opentelemetry-collector-contrib:0.71.0","opentelemetry-targetallocator":"ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.70.0","operator-opamp-bridge":"ghcr.io/open-telemetry/opentelemetry-operator/operator-opamp-bridge:0.70.0","auto-instrumentation-java":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.23.0","auto-instrumentation-nodejs":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.34.0","auto-instrumentation-python":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.36b0","auto-instrumentation-dotnet":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.5.0","build-date":"2023-02-17T18:14:37Z","go-version":"go1.19.6","go-arch":"amd64","go-os":"linux","labels-filter":[]}
{"level":"info","ts":1678814628.1473424,"logger":"setup","msg":"the env var WATCH_NAMESPACE isn't set, watching all namespaces"}
I0314 17:23:49.197546       1 request.go:682] Waited for 1.042404732s due to client-side throttling, not priority and fairness, request: GET:https://100.64.0.1:443/apis/scheduling.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":1678814630.550974,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"0.0.0.0:9080"}
{"level":"info","ts":1678814630.5549319,"logger":"controller-runtime.builder","msg":"Registering a mutating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector","path":"/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1678814630.554996,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1678814630.5550349,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=OpenTelemetryCollector","path":"/validate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1678814630.5550835,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-opentelemetry-io-v1alpha1-opentelemetrycollector"}
{"level":"info","ts":1678814630.5551398,"logger":"controller-runtime.builder","msg":"Registering a mutating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=Instrumentation","path":"/mutate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1678814630.5551703,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1678814630.5551999,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"opentelemetry.io/v1alpha1, Kind=Instrumentation","path":"/validate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1678814630.555227,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-opentelemetry-io-v1alpha1-instrumentation"}
{"level":"info","ts":1678814630.555288,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1678814630.5553153,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1678814630.555375,"logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
{"level":"info","ts":1678814630.5554013,"msg":"Starting server","kind":"health probe","addr":"[::]:9081"}
{"level":"info","ts":1678814630.5554013,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:9080"}
{"level":"info","ts":1678814630.555537,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
I0314 17:23:50.555559       1 leaderelection.go:248] attempting to acquire leader lease sre/9f7554c3.opentelemetry.io...
{"level":"info","ts":1678814630.5555897,"logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":1678814630.5556242,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
```
