### ISSUE TITLE
[auto-instrumentation-python] Fails to startup 

### ISSUE THREAD

**Issue by joeriddles** [open-telemetry/opentelemetry-operator#2448]
### Component(s)

instrumentation

## Description
When running the auto instrumentation, it fails to start.

## Steps to Reproduce

Run the following
```
export OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true && \
	opentelemetry-instrument \
	  --traces_exporter otlp \
	  --metrics_exporter otlp \
	  --metric_export_interval 1000 \
	  --exporter_otlp_protocol 'http/protobuf' \
	  --exporter_otlp_endpoint 'http://localhost:4318' \
	  --service_name main \
	  uvicorn main:app
```

## Expected Result
No errors

## Actual Result
The configuration fails to be loaded.

### Kubernetes Version

N/A

### Operator version

0.42b0

### Collector version

0.42b0

## Environment
MacOS Sonoma 14.1 (23B74)
Python 3.12

### Log output

```shell
export OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true && \
        opentelemetry-instrument \
          --traces_exporter otlp \
          --metrics_exporter otlp \
          --metric_export_interval 1000 \
          --exporter_otlp_protocol 'http/protobuf' \
          --exporter_otlp_endpoint 'http://localhost:4318' \
          --service_name main \
          uvicorn main:app
Configuration of configurator failed
Traceback (most recent call last):
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 102, in _import_config_components
    next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py", line 113, in _load_configurators
    entry_point.load()().configure(auto_instrumentation_version=__version__)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 406, in configure
    self._configure(**kwargs)
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 422, in _configure
    _initialize_components(kwargs.get("auto_instrumentation_version"))
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 349, in _initialize_components
    trace_exporters, metric_exporters, log_exporters = _import_exporters(
                                                       ^^^^^^^^^^^^^^^^^^
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 268, in _import_exporters
    for (exporter_name, exporter_impl,) in _import_config_components(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 119, in _import_config_components
    raise RuntimeError(
RuntimeError: Requested component 'otlp_proto_http' not found in entry point 'opentelemetry_traces_exporter'
Failed to auto initialize opentelemetry
Traceback (most recent call last):
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 102, in _import_config_components
    next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 38, in initialize
    _load_configurators()
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py", line 124, in _load_configurators
    raise exc
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py", line 113, in _load_configurators
    entry_point.load()().configure(auto_instrumentation_version=__version__)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 406, in configure
    self._configure(**kwargs)
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 422, in _configure
    _initialize_components(kwargs.get("auto_instrumentation_version"))
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 349, in _initialize_components
    trace_exporters, metric_exporters, log_exporters = _import_exporters(
                                                       ^^^^^^^^^^^^^^^^^^
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 268, in _import_exporters
    for (exporter_name, exporter_impl,) in _import_config_components(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josephriddle/source/python/otel-demo/.venv/lib/python3.12/site-packages/opentelemetry/sdk/_configuration/__init__.py", line 119, in _import_config_components
    raise RuntimeError(
RuntimeError: Requested component 'otlp_proto_http' not found in entry point 'opentelemetry_traces_exporter'
INFO:     Started server process [89695]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

**Comment by joeriddles** [comment]
Solved by `pip install opentelemetry-exporter-otlp-proto-http==1.21.0`
