### ISSUE TITLE
Python flask is not able to auto instrument

### ISSUE THREAD

**Issue by subbusquareshift** [open-telemetry/opentelemetry-operator#654]
Failed to load configured propagators

```
Traceback (most recent call last):
  File "/otel-auto-instrumentation/opentelemetry/propagate/__init__.py", line 136, in <module>
    next(  # type: ignore
StopIteration
Instrumenting of flask failed
Traceback (most recent call last):
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 84, in _load_instrumentors
    distro.load_instrumentor(entry_point, skip_dep_check=True)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/distro.py", line 62, in load_instrumentor
    instrumentor: BaseInstrumentor = entry_point.load()
  File "/otel-auto-instrumentation/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/otel-auto-instrumentation/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/flask/__init__.py", line 97, in <module>
    import opentelemetry.instrumentation.wsgi as otel_wsgi
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/wsgi/__init__.py", line 114, in <module>
    from opentelemetry.propagate import extract
  File "/otel-auto-instrumentation/opentelemetry/propagate/__init__.py", line 136, in <module>
    next(  # type: ignore
StopIteration
Failed to auto initialize opentelemetry
Traceback (most recent call last):
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 117, in initialize
    _load_instrumentors(distro)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 88, in _load_instrumentors
    raise exc
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 84, in _load_instrumentors
    distro.load_instrumentor(entry_point, skip_dep_check=True)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/distro.py", line 62, in load_instrumentor
    instrumentor: BaseInstrumentor = entry_point.load()
  File "/otel-auto-instrumentation/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/otel-auto-instrumentation/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/flask/__init__.py", line 97, in <module>
    import opentelemetry.instrumentation.wsgi as otel_wsgi
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/wsgi/__init__.py", line 114, in <module>
    from opentelemetry.propagate import extract
  File "/otel-auto-instrumentation/opentelemetry/propagate/__init__.py", line 136, in <module>
    next(  # type: ignore
StopIteration
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 ```

**Comment by jpkrohling** [comment]
cc @pavolloffay, @anuraaga, could one of you address this?

**Comment by anuraaga** [comment]
@subbusquareshift Are you able to share a reproduction app to try with? If not, can you share information about the app such as flask version, docker base image?

**Comment by subbusquareshift** [comment]
sponmuth/my_flask_app

**Comment by subbusquareshift** [comment]
Are you able to replicate the issue ?

**Comment by subbusquareshift** [comment]
Any findings on this ?

**Comment by anuraaga** [comment]
Sorry haven't been able to take a look at it yet but will check this week. Thanks for the patience

**Comment by pavolloffay** [comment]
@anuraaga this issue might be related to https://github.com/open-telemetry/opentelemetry-operator/issues/682

**Comment by mat-rumian** [comment]
Beside propagators issue mentioned here - https://github.com/open-telemetry/opentelemetry-operator/issues/682#issuecomment-1026128843
If your Flask application has `debug=true` then there's known problem with instrumentation - it doesn't work. Set `debug=False` and your instrumentation should work fine.

**Comment by anuraaga** [comment]
Sorry for not following up, @mat-rumian thanks a lot for the help!

**Comment by pavolloffay** [comment]
In that case #684 will resolve this issue for propagators. I don't think we can control `debug=false` in the operator.

**Comment by pavolloffay** [comment]
Closing as we cannot control `debug=*` in the operator. Please refer to the https://github.com/open-telemetry/opentelemetry-python-contrib/issues/546 and continue discussion there. 

Please re-open if you think otherwise.
